/**
 * 核心词库：三级难度
 * lv: 1=入门(最常用界面词) 2=进阶 3=高级
 * 结构: { "中文词": { en: "English", lv: 1 } }
 * 本词库优先于 CC-CEDICT 扩展词库，保证高频界面词翻译精炼。
 */
globalThis.LE_DICT_CORE = {
  // ============ L1 入门：界面基础词 ============
  "搜索": { en: "Search", lv: 1 },
  "测试": { en: "Test", lv: 1 },
  "欢迎": { en: "Welcome", lv: 1 },
  "网站": { en: "Website", lv: 1 },
  "站点": { en: "Site", lv: 1 },
  "网页": { en: "Webpage", lv: 1 },
  "文章": { en: "Article", lv: 1 },
  "搜索框": { en: "Search Box", lv: 1 },
  "热搜": { en: "Trending", lv: 1 },
  "搜索历史": { en: "Search History", lv: 2 },
  "登录": { en: "Login", lv: 1 },
  "注册": { en: "Sign Up", lv: 1 },
  "退出登录": { en: "Log Out", lv: 1 },
  "账号": { en: "Account", lv: 1 },
  "账户": { en: "Account", lv: 1 },
  "密码": { en: "Password", lv: 1 },
  "验证码": { en: "Captcha", lv: 1 },
  "忘记密码": { en: "Forgot Password", lv: 1 },
  "记住我": { en: "Remember Me", lv: 1 },
  "自动登录": { en: "Auto Login", lv: 2 },
  "首页": { en: "Home", lv: 1 },
  "我的": { en: "My", lv: 1 },
  "个人中心": { en: "My Account", lv: 1 },
  "个人资料": { en: "Profile", lv: 1 },
  "设置": { en: "Settings", lv: 1 },
  "消息": { en: "Messages", lv: 1 },
  "通知": { en: "Notifications", lv: 1 },
  "收藏": { en: "Favorite", lv: 1 },
  "点击": { en: "Click", lv: 1 },
  "按钮": { en: "Button", lv: 1 },
  "信息": { en: "Info", lv: 1 },
  "输入": { en: "Enter", lv: 1 },
  "选择": { en: "Select", lv: 1 },
  "加载": { en: "Loading", lv: 1 },
  "内容": { en: "Content", lv: 1 },
  "名称": { en: "Name", lv: 1 },
  "类型": { en: "Type", lv: 1 },
  "状态": { en: "Status", lv: 1 },
  "数据": { en: "Data", lv: 1 },
  "用户": { en: "User", lv: 1 },
  "系统": { en: "System", lv: 1 },
  "操作": { en: "Action", lv: 1 },
  "功能": { en: "Feature", lv: 1 },
  "选项": { en: "Option", lv: 1 },
  "列表": { en: "List", lv: 1 },
  "页面": { en: "Page", lv: 1 },
  "窗口": { en: "Window", lv: 1 },
  "屏幕": { en: "Screen", lv: 1 },
  "菜单": { en: "Menu", lv: 1 },
  "应用": { en: "App", lv: 1 },
  "服务": { en: "Service", lv: 1 },
  "连接": { en: "Connect", lv: 1 },
  "断开": { en: "Disconnect", lv: 1 },
  "成功": { en: "Success", lv: 1 },
  "失败": { en: "Failure", lv: 1 },
  "错误": { en: "Error", lv: 1 },
  "允许": { en: "Allow", lv: 1 },
  "禁止": { en: "Forbid", lv: 1 },
  "收藏夹": { en: "Favorites", lv: 1 },
  "历史": { en: "History", lv: 1 },
  "浏览记录": { en: "Browsing History", lv: 1 },
  "购物车": { en: "Cart", lv: 1 },
  "订单": { en: "Order", lv: 1 },
  "我的订单": { en: "My Orders", lv: 1 },
  "支付": { en: "Pay", lv: 1 },
  "立即支付": { en: "Pay Now", lv: 1 },
  "确认订单": { en: "Confirm Order", lv: 1 },
  "提交订单": { en: "Place Order", lv: 1 },
  "立即购买": { en: "Buy Now", lv: 1 },
  "加入购物车": { en: "Add to Cart", lv: 1 },
  "结算": { en: "Checkout", lv: 1 },
  "付款": { en: "Payment", lv: 1 },
  "退款": { en: "Refund", lv: 1 },
  "发货": { en: "Ship", lv: 1 },
  "物流": { en: "Logistics", lv: 1 },
  "签收": { en: "Sign For", lv: 1 },
  "收货地址": { en: "Shipping Address", lv: 1 },
  "默认地址": { en: "Default Address", lv: 2 },
  "评价": { en: "Review", lv: 1 },
  "返回": { en: "Back", lv: 1 },
  "退出": { en: "Exit", lv: 1 },
  "确认": { en: "Confirm", lv: 1 },
  "取消": { en: "Cancel", lv: 1 },
  "保存": { en: "Save", lv: 1 },
  "删除": { en: "Delete", lv: 1 },
  "编辑": { en: "Edit", lv: 1 },
  "添加": { en: "Add", lv: 1 },
  "新建": { en: "New", lv: 1 },
  "创建": { en: "Create", lv: 1 },
  "查看": { en: "View", lv: 1 },
  "详情": { en: "Details", lv: 1 },
  "下载": { en: "Download", lv: 1 },
  "上传": { en: "Upload", lv: 1 },
  "分享": { en: "Share", lv: 1 },
  "转发": { en: "Forward", lv: 1 },
  "复制": { en: "Copy", lv: 1 },
  "粘贴": { en: "Paste", lv: 1 },
  "剪切": { en: "Cut", lv: 1 },
  "全选": { en: "Select All", lv: 1 },
  "清空": { en: "Clear", lv: 1 },
  "刷新": { en: "Refresh", lv: 1 },
  "更多": { en: "More", lv: 1 },
  "全部": { en: "All", lv: 1 },
  "完成": { en: "Done", lv: 1 },
  "跳过": { en: "Skip", lv: 1 },
  "继续": { en: "Continue", lv: 1 },
  "下一步": { en: "Next", lv: 1 },
  "上一步": { en: "Previous", lv: 1 },
  "关闭": { en: "Close", lv: 1 },
  "打开": { en: "Open", lv: 1 },
  "帮助": { en: "Help", lv: 1 },
  "帮助中心": { en: "Support Center", lv: 1 },
  "客服": { en: "Support", lv: 1 },
  "咨询": { en: "Consult", lv: 1 },
  "反馈": { en: "Feedback", lv: 1 },
  "意见反馈": { en: "Feedback", lv: 1 },
  "常见问题": { en: "FAQ", lv: 1 },
  "关于我们": { en: "About Us", lv: 1 },
  "联系我们": { en: "Contact Us", lv: 1 },
  "使用协议": { en: "Terms of Use", lv: 2 },
  "服务条款": { en: "Terms of Service", lv: 2 },
  "隐私政策": { en: "Privacy Policy", lv: 2 },
  "版本": { en: "Version", lv: 1 },
  "更新": { en: "Update", lv: 1 },
  "检查更新": { en: "Check for Updates", lv: 1 },
  "语言": { en: "Language", lv: 1 },
  "中文": { en: "Chinese", lv: 1 },
  "英文": { en: "English", lv: 1 },
  "字体": { en: "Font", lv: 1 },
  "大小": { en: "Size", lv: 1 },
  "主题": { en: "Theme", lv: 1 },
  "深色模式": { en: "Dark Mode", lv: 2 },
  "浅色模式": { en: "Light Mode", lv: 2 },
  "声音": { en: "Sound", lv: 1 },
  "震动": { en: "Vibration", lv: 1 },
  "网络": { en: "Network", lv: 1 },
  "缓存": { en: "Cache", lv: 1 },
  "清除缓存": { en: "Clear Cache", lv: 1 },
  "存储": { en: "Storage", lv: 1 },
  "空间": { en: "Space", lv: 1 },
  "时间": { en: "Time", lv: 1 },
  "日期": { en: "Date", lv: 1 },
  "日历": { en: "Calendar", lv: 1 },
  "闹钟": { en: "Alarm", lv: 1 },
  "天气": { en: "Weather", lv: 1 },
  "音乐": { en: "Music", lv: 1 },
  "视频": { en: "Video", lv: 1 },
  "图片": { en: "Image", lv: 1 },
  "照片": { en: "Photo", lv: 1 },
  "相机": { en: "Camera", lv: 1 },
  "相册": { en: "Album", lv: 1 },
  "文件": { en: "File", lv: 1 },
  "文档": { en: "Document", lv: 1 },
  "下载管理": { en: "Downloads", lv: 1 },
  "云盘": { en: "Cloud Drive", lv: 1 },
  "网盘": { en: "Cloud Drive", lv: 1 },
  "同步": { en: "Sync", lv: 1 },
  "备份": { en: "Backup", lv: 1 },
  "恢复": { en: "Restore", lv: 1 },
  "重启": { en: "Restart", lv: 1 },
  "打印": { en: "Print", lv: 1 },
  "复制链接": { en: "Copy Link", lv: 1 },
  "打开链接": { en: "Open Link", lv: 1 },
  "扫描": { en: "Scan", lv: 1 },
  "扫码": { en: "Scan QR", lv: 1 },
  "二维码": { en: "QR Code", lv: 1 },
  "支付密码": { en: "Payment Password", lv: 2 },
  "修改密码": { en: "Change Password", lv: 1 },
  "更换头像": { en: "Change Avatar", lv: 1 },
  "修改资料": { en: "Edit Profile", lv: 1 },
  "昵称": { en: "Nickname", lv: 1 },
  "性别": { en: "Gender", lv: 1 },
  "生日": { en: "Birthday", lv: 1 },
  "地区": { en: "Region", lv: 1 },
  "签名": { en: "Signature", lv: 1 },
  "重新登录": { en: "Log In Again", lv: 1 },
  "登录失败": { en: "Login Failed", lv: 1 },
  "登录成功": { en: "Login Successful", lv: 1 },
  "网络错误": { en: "Network Error", lv: 1 },
  "加载失败": { en: "Load Failed", lv: 1 },
  "重试": { en: "Retry", lv: 1 },
  "稍后再说": { en: "Later", lv: 1 },
  "知道了": { en: "Got It", lv: 1 },
  "好的": { en: "OK", lv: 1 },
  "确定": { en: "OK", lv: 1 },
  "不同意": { en: "Disagree", lv: 1 },
  "同意并继续": { en: "Agree and Continue", lv: 1 },
  "立即体验": { en: "Try Now", lv: 1 },
  "开始使用": { en: "Get Started", lv: 1 },
  "欢迎使用": { en: "Welcome", lv: 1 },
  "请输入": { en: "Please Enter", lv: 1 },
  "请选择": { en: "Please Select", lv: 1 },
  "用户名": { en: "Username", lv: 1 },
  "手机号": { en: "Phone Number", lv: 1 },
  "邮箱": { en: "Email", lv: 1 },
  "姓名": { en: "Name", lv: 1 },
  "性别": { en: "Gender", lv: 1 },
  "地址": { en: "Address", lv: 1 },
  "电话": { en: "Phone", lv: 1 },
  "数量": { en: "Quantity", lv: 1 },
  "价格": { en: "Price", lv: 1 },
  "总价": { en: "Total", lv: 1 },
  "合计": { en: "Total", lv: 1 },
  "优惠": { en: "Discount", lv: 1 },
  "折扣": { en: "Discount", lv: 2 },
  "运费": { en: "Shipping Fee", lv: 1 },
  "包邮": { en: "Free Shipping", lv: 1 },
  "免运费": { en: "Free Shipping", lv: 1 },
  "库存": { en: "Stock", lv: 1 },
  "商品": { en: "Product", lv: 1 },
  "商品详情": { en: "Product Details", lv: 1 },
  "加入收藏": { en: "Add to Favorites", lv: 1 },
  "关注": { en: "Follow", lv: 1 },
  "已关注": { en: "Following", lv: 1 },
  "粉丝": { en: "Followers", lv: 1 },
  "点赞": { en: "Like", lv: 1 },
  "评论": { en: "Comment", lv: 1 },
  "回复": { en: "Reply", lv: 1 },
  "发布": { en: "Post", lv: 1 },
  "动态": { en: "Moments", lv: 1 },
  "消息中心": { en: "Message Center", lv: 1 },
  "系统消息": { en: "System Message", lv: 1 },
  "我的收藏": { en: "My Favorites", lv: 1 },
  "我的钱包": { en: "My Wallet", lv: 2 },
  "余额": { en: "Balance", lv: 1 },
  "充值": { en: "Top Up", lv: 1 },
  "提现": { en: "Withdraw", lv: 1 },
  "账单": { en: "Bill", lv: 1 },
  "明细": { en: "Details", lv: 1 },
  "收益": { en: "Earnings", lv: 1 },
  "积分": { en: "Points", lv: 1 },
  "金币": { en: "Coins", lv: 1 },
  "等级": { en: "Level", lv: 1 },
  "会员": { en: "VIP", lv: 1 },
  "开通会员": { en: "Get VIP", lv: 2 },
  "续费": { en: "Renew", lv: 2 },
  "自动续费": { en: "Auto-Renew", lv: 2 },
  "权益": { en: "Benefits", lv: 2 },
  "专享": { en: "Exclusive", lv: 2 },
  "特权": { en: "Privileges", lv: 2 },
  "兑换": { en: "Redeem", lv: 2 },
  "积分兑换": { en: "Points Redemption", lv: 2 },
  "邀请码": { en: "Invite Code", lv: 2 },
  "优惠券": { en: "Coupon", lv: 2 },
  "满减": { en: "Spend & Save", lv: 2 },
  "特价": { en: "Special Offer", lv: 2 },
  "秒杀": { en: "Flash Sale", lv: 2 },
  "限时抢购": { en: "Limited Time", lv: 2 },
  "发票": { en: "Invoice", lv: 1 },
  "电子发票": { en: "E-Invoice", lv: 2 },
  "售后": { en: "After-Sales", lv: 1 },
  "退货": { en: "Return", lv: 1 },
  "换货": { en: "Exchange", lv: 1 },
  "七天无理由": { en: "7-Day Return", lv: 2 },
  "质保": { en: "Warranty", lv: 2 },
  "保修": { en: "Warranty", lv: 2 },
  "客服中心": { en: "Support Center", lv: 1 },
  "投诉": { en: "Complaint", lv: 1 },
  "举报": { en: "Report", lv: 1 },

  // ============ L2 进阶 ============
  "订阅": { en: "Subscribe", lv: 2 },
  "取消订阅": { en: "Unsubscribe", lv: 2 },
  "取关": { en: "Unfollow", lv: 2 },
  "取消关注": { en: "Unfollow", lv: 2 },
  "置顶": { en: "Pin", lv: 2 },
  "取消置顶": { en: "Unpin", lv: 2 },
  "精华": { en: "Featured", lv: 2 },
  "热门": { en: "Hot", lv: 2 },
  "推荐": { en: "Recommended", lv: 2 },
  "排行榜": { en: "Ranking", lv: 2 },
  "话题": { en: "Topic", lv: 2 },
  "圈子": { en: "Circle", lv: 2 },
  "小组": { en: "Group", lv: 2 },
  "私信": { en: "Direct Message", lv: 2 },
  "踩": { en: "Dislike", lv: 2 },
  "拉黑": { en: "Block", lv: 2 },
  "屏蔽": { en: "Block", lv: 2 },
  "关注列表": { en: "Following List", lv: 2 },
  "粉丝列表": { en: "Follower List", lv: 2 },
  "草稿": { en: "Draft", lv: 2 },
  "定时发布": { en: "Schedule Post", lv: 2 },
  "设为私密": { en: "Make Private", lv: 2 },
  "可见范围": { en: "Visibility", lv: 2 },
  "谁可以看": { en: "Who Can See", lv: 2 },
  "朋友圈": { en: "Moments", lv: 2 },
  "群聊": { en: "Group Chat", lv: 2 },
  "发起群聊": { en: "New Group Chat", lv: 2 },
  "群名称": { en: "Group Name", lv: 2 },
  "群公告": { en: "Group Announcement", lv: 2 },
  "群成员": { en: "Group Members", lv: 2 },
  "退群": { en: "Leave Group", lv: 2 },
  "解散": { en: "Dismiss", lv: 2 },
  "加入群聊": { en: "Join Group", lv: 2 },
  "消息免打扰": { en: "Mute", lv: 2 },
  "已读": { en: "Read", lv: 2 },
  "未读": { en: "Unread", lv: 2 },
  "送达": { en: "Delivered", lv: 2 },
  "撤回": { en: "Recall", lv: 2 },
  "引用": { en: "Quote", lv: 2 },
  "表情": { en: "Emoji", lv: 2 },
  "视频通话": { en: "Video Call", lv: 2 },
  "语音通话": { en: "Voice Call", lv: 2 },
  "语音消息": { en: "Voice Message", lv: 2 },
  "转文字": { en: "Text", lv: 2 },
  "位置共享": { en: "Share Location", lv: 2 },
  "实时位置": { en: "Live Location", lv: 2 },
  "附近的人": { en: "Nearby", lv: 2 },
  "加好友": { en: "Add Friend", lv: 2 },
  "好友申请": { en: "Friend Request", lv: 2 },
  "通过": { en: "Accept", lv: 2 },
  "拒绝": { en: "Decline", lv: 2 },
  "删除好友": { en: "Remove Friend", lv: 2 },
  "黑名单": { en: "Blacklist", lv: 2 },
  "账号与安全": { en: "Account & Security", lv: 2 },
  "登录设备": { en: "Logged-in Devices", lv: 2 },
  "异地登录": { en: "Login Elsewhere", lv: 2 },
  "账号注销": { en: "Delete Account", lv: 2 },
  "隐私设置": { en: "Privacy Settings", lv: 2 },
  "公开": { en: "Public", lv: 2 },
  "仅自己可见": { en: "Only Me", lv: 2 },
  "部分可见": { en: "Partial Visibility", lv: 2 },
  "不给谁看": { en: "Hide From", lv: 2 },
  "通知设置": { en: "Notification Settings", lv: 2 },
  "接收通知": { en: "Receive Notifications", lv: 2 },
  "推送通知": { en: "Push Notifications", lv: 2 },
  "站内信": { en: "Inbox Message", lv: 2 },
  "邮件通知": { en: "Email Notifications", lv: 2 },
  "短信通知": { en: "SMS Notifications", lv: 2 },
  "自动回复": { en: "Auto-Reply", lv: 2 },
  "消息提醒": { en: "Message Alerts", lv: 2 },
  "找回密码": { en: "Recover Password", lv: 2 },
  "更改密码": { en: "Change Password", lv: 2 },
  "确认密码": { en: "Confirm Password", lv: 2 },
  "新密码": { en: "New Password", lv: 2 },
  "旧密码": { en: "Old Password", lv: 2 },
  "退出账号": { en: "Sign Out", lv: 2 },
  "多设备登录": { en: "Multi-Device Login", lv: 2 },
  "设备管理": { en: "Device Management", lv: 2 },
  "安全中心": { en: "Security Center", lv: 2 },
  "密保问题": { en: "Security Questions", lv: 2 },
  "实名认证": { en: "Real-Name Verification", lv: 3 },
  "认证": { en: "Verification", lv: 2 },
  "审核": { en: "Review", lv: 2 },
  "审核中": { en: "Under Review", lv: 2 },
  "审核通过": { en: "Approved", lv: 2 },
  "审核失败": { en: "Rejected", lv: 2 },
  "申诉": { en: "Appeal", lv: 2 },
  "人工审核": { en: "Manual Review", lv: 2 },
  "投诉渠道": { en: "Complaint Channel", lv: 2 },
  "举报中心": { en: "Report Center", lv: 2 },
  "青少年模式": { en: "Teen Mode", lv: 3 },
  "防沉迷": { en: "Anti-Addiction", lv: 3 },
  "健康使用": { en: "Digital Wellbeing", lv: 3 },
  "屏幕时间": { en: "Screen Time", lv: 3 },
  "应用限额": { en: "App Limits", lv: 3 },
  "时间管理": { en: "Time Management", lv: 3 },
  "订单详情": { en: "Order Details", lv: 2 },
  "交易记录": { en: "Transaction History", lv: 2 },
  "资金明细": { en: "Fund Details", lv: 2 },
  "账户余额": { en: "Account Balance", lv: 2 },
  "可用余额": { en: "Available Balance", lv: 2 },
  "冻结金额": { en: "Frozen Amount", lv: 2 },
  "银行卡": { en: "Bank Card", lv: 2 },
  "绑定银行卡": { en: "Link Bank Card", lv: 2 },
  "解绑": { en: "Unlink", lv: 2 },
  "支付方式": { en: "Payment Method", lv: 2 },
  "微信支付": { en: "WeChat Pay", lv: 2 },
  "余额支付": { en: "Balance Pay", lv: 2 },
  "免密支付": { en: "Password-Free Pay", lv: 3 },
  "指纹支付": { en: "Fingerprint Pay", lv: 3 },
  "面容支付": { en: "Face Pay", lv: 3 },
  "优惠码": { en: "Promo Code", lv: 2 },
  "优惠券包": { en: "Coupon Pack", lv: 2 },
  "领取": { en: "Claim", lv: 2 },
  "已领取": { en: "Claimed", lv: 2 },
  "使用": { en: "Use", lv: 2 },
  "已使用": { en: "Used", lv: 2 },
  "已过期": { en: "Expired", lv: 2 },
  "有效期": { en: "Valid Until", lv: 2 },
  "满减券": { en: "Discount Coupon", lv: 2 },
  "促销": { en: "Promotion", lv: 2 },
  "活动": { en: "Event", lv: 2 },
  "参与": { en: "Join", lv: 2 },
  "报名": { en: "Sign Up", lv: 2 },
  "抽奖": { en: "Lucky Draw", lv: 2 },
  "中奖": { en: "Win", lv: 2 },
  "奖品": { en: "Prize", lv: 2 },
  "打卡": { en: "Check In", lv: 2 },
  "签到": { en: "Check In", lv: 2 },
  "连续签到": { en: "Streak", lv: 2 },
  "任务": { en: "Tasks", lv: 2 },
  "每日任务": { en: "Daily Tasks", lv: 2 },
  "成就": { en: "Achievements", lv: 2 },
  "勋章": { en: "Badge", lv: 2 },
  "经验值": { en: "XP", lv: 2 },
  "成长值": { en: "Growth Points", lv: 2 },
  "排行榜": { en: "Leaderboard", lv: 2 },
  "邀请好友": { en: "Invite Friends", lv: 2 },
  "分享有礼": { en: "Share & Earn", lv: 2 },
  "签到奖励": { en: "Check-in Reward", lv: 2 },
  "任务中心": { en: "Task Center", lv: 2 },
  "成长体系": { en: "Growth System", lv: 3 },
  "会员到期": { en: "Membership Expired", lv: 2 },
  "取消续费": { en: "Cancel Renewal", lv: 2 },
  "会员权益": { en: "VIP Benefits", lv: 2 },
  "尊享": { en: "Premium", lv: 2 },
  "赠送": { en: "Gift", lv: 2 },
  "赠送好友": { en: "Gift to Friend", lv: 2 },
  "待付款": { en: "Pending Payment", lv: 2 },
  "待发货": { en: "Pending Shipment", lv: 2 },
  "待收货": { en: "Pending Delivery", lv: 2 },
  "待评价": { en: "Pending Review", lv: 2 },
  "已完成": { en: "Completed", lv: 2 },
  "已取消": { en: "Cancelled", lv: 2 },
  "进行中": { en: "In Progress", lv: 2 },
  "即将开始": { en: "Upcoming", lv: 2 },
  "已结束": { en: "Ended", lv: 2 },
  "购物清单": { en: "Shopping List", lv: 2 },
  "心愿单": { en: "Wishlist", lv: 2 },
  "足迹": { en: "Footprints", lv: 2 },
  "常购清单": { en: "Frequent Purchases", lv: 2 },
  "相似商品": { en: "Similar Products", lv: 2 },
  "相关推荐": { en: "Related Recommendations", lv: 2 },
  "猜你喜欢": { en: "Recommended for You", lv: 2 },
  "为你推荐": { en: "For You", lv: 2 },
  "新品": { en: "New Arrivals", lv: 2 },
  "热卖": { en: "Best Sellers", lv: 2 },
  "畅销": { en: "Best Selling", lv: 2 },
  "好评": { en: "Positive Review", lv: 2 },
  "差评": { en: "Negative Review", lv: 2 },
  "中评": { en: "Neutral Review", lv: 2 },
  "好评率": { en: "Positive Rate", lv: 2 },
  "销量": { en: "Sales", lv: 2 },
  "月销": { en: "Monthly Sales", lv: 2 },
  "累计评价": { en: "Total Reviews", lv: 2 },
  "有图": { en: "With Photos", lv: 2 },
  "追评": { en: "Follow-up Review", lv: 2 },
  "晒单": { en: "Share Purchase", lv: 2 },
  "评价有礼": { en: "Review & Earn", lv: 2 },
  "仅退款": { en: "Refund Only", lv: 2 },
  "退货退款": { en: "Return & Refund", lv: 2 },
  "换货申请": { en: "Exchange Request", lv: 2 },
  "维修": { en: "Repair", lv: 2 },
  "安装": { en: "Install", lv: 2 },
  "卸载": { en: "Uninstall", lv: 2 },
  "重新安装": { en: "Reinstall", lv: 2 },
  "恢复出厂设置": { en: "Factory Reset", lv: 3 },
  "更新日志": { en: "Changelog", lv: 2 },
  "版本号": { en: "Version Number", lv: 2 },
  "当前版本": { en: "Current Version", lv: 2 },
  "最新版本": { en: "Latest Version", lv: 2 },
  "新功能": { en: "New Features", lv: 2 },
  "优化": { en: "Optimization", lv: 2 },
  "修复": { en: "Fix", lv: 2 },
  "已知问题": { en: "Known Issues", lv: 2 },
  "功能说明": { en: "Features", lv: 2 },
  "使用帮助": { en: "User Guide", lv: 2 },
  "操作指南": { en: "Guide", lv: 2 },
  "教程": { en: "Tutorial", lv: 2 },
  "示例": { en: "Example", lv: 2 },
  "演示": { en: "Demo", lv: 2 },

  // ============ L3 高级 ============
  "审阅": { en: "Review", lv: 3 },
  "复核": { en: "Recheck", lv: 3 },
  "归档": { en: "Archive", lv: 3 },
  "批量操作": { en: "Batch Actions", lv: 3 },
  "多选": { en: "Multi-Select", lv: 3 },
  "反选": { en: "Invert Selection", lv: 3 },
  "排序": { en: "Sort", lv: 3 },
  "筛选": { en: "Filter", lv: 3 },
  "条件": { en: "Criteria", lv: 3 },
  "高级筛选": { en: "Advanced Filter", lv: 3 },
  "导出": { en: "Export", lv: 3 },
  "导入": { en: "Import", lv: 3 },
  "导出数据": { en: "Export Data", lv: 3 },
  "导入数据": { en: "Import Data", lv: 3 },
  "数据同步": { en: "Data Sync", lv: 3 },
  "数据备份": { en: "Data Backup", lv: 3 },
  "数据恢复": { en: "Data Recovery", lv: 3 },
  "系统设置": { en: "System Settings", lv: 3 },
  "应用管理": { en: "App Management", lv: 3 },
  "权限管理": { en: "Permission Management", lv: 3 },
  "通知权限": { en: "Notification Permission", lv: 3 },
  "位置权限": { en: "Location Permission", lv: 3 },
  "相机权限": { en: "Camera Permission", lv: 3 },
  "麦克风权限": { en: "Microphone Permission", lv: 3 },
  "存储权限": { en: "Storage Permission", lv: 3 },
  "通讯录权限": { en: "Contacts Permission", lv: 3 },
  "自启动": { en: "Auto-Start", lv: 3 },
  "后台运行": { en: "Background Running", lv: 3 },
  "电池优化": { en: "Battery Optimization", lv: 3 },
  "省电模式": { en: "Power Saving", lv: 3 },
  "性能模式": { en: "Performance Mode", lv: 3 },
  "游戏模式": { en: "Game Mode", lv: 3 },
  "开发者选项": { en: "Developer Options", lv: 3 },
  "USB调试": { en: "USB Debugging", lv: 3 },
  "模拟定位": { en: "Mock Location", lv: 3 },
  "无障碍": { en: "Accessibility", lv: 3 },
  "辅助功能": { en: "Accessibility", lv: 3 },
  "悬浮窗": { en: "Floating Window", lv: 3 },
  "分屏": { en: "Split Screen", lv: 3 },
  "小窗": { en: "Mini Window", lv: 3 },
  "画中画": { en: "Picture-in-Picture", lv: 3 },
  "多任务": { en: "Multitasking", lv: 3 },
  "最近任务": { en: "Recent Tasks", lv: 3 },
  "清理后台": { en: "Clear Background", lv: 3 },
  "加速": { en: "Boost", lv: 3 },
  "内存": { en: "Memory", lv: 3 },
  "占用": { en: "Usage", lv: 3 },
  "释放": { en: "Free Up", lv: 3 },
  "缓存文件": { en: "Cache Files", lv: 3 },
  "临时文件": { en: "Temp Files", lv: 3 },
  "残留": { en: "Residual Files", lv: 3 },
  "覆盖安装": { en: "Overwrite Install", lv: 3 },
  "构建号": { en: "Build Number", lv: 3 },
  "系统版本": { en: "System Version", lv: 3 },
  "固件": { en: "Firmware", lv: 3 },
  "驱动程序": { en: "Driver", lv: 3 },
  "兼容性": { en: "Compatibility", lv: 3 },
  "兼容模式": { en: "Compatibility Mode", lv: 3 },
  "横屏": { en: "Landscape", lv: 3 },
  "竖屏": { en: "Portrait", lv: 3 },
  "自动旋转": { en: "Auto-Rotate", lv: 3 },
  "屏幕亮度": { en: "Brightness", lv: 3 },
  "护眼模式": { en: "Eye Comfort", lv: 3 },
  "夜间模式": { en: "Night Mode", lv: 3 },
  "高对比度": { en: "High Contrast", lv: 3 },
  "字体大小": { en: "Font Size", lv: 3 },
  "字体样式": { en: "Font Style", lv: 3 },
  "行间距": { en: "Line Spacing", lv: 3 },
  "字间距": { en: "Letter Spacing", lv: 3 },
  "阅读模式": { en: "Reader Mode", lv: 3 },
  "沉浸模式": { en: "Immersive Mode", lv: 3 },
  "全屏": { en: "Fullscreen", lv: 3 },
  "退出全屏": { en: "Exit Fullscreen", lv: 3 },
  "快捷键": { en: "Shortcut", lv: 3 },
  "快捷键设置": { en: "Shortcut Settings", lv: 3 },
  "键盘": { en: "Keyboard", lv: 3 },
  "鼠标": { en: "Mouse", lv: 3 },
  "触摸板": { en: "Touchpad", lv: 3 },
  "外接设备": { en: "External Device", lv: 3 },
  "默认应用": { en: "Default Apps", lv: 3 },
  "打开方式": { en: "Open With", lv: 3 },
  "关联": { en: "Association", lv: 3 },
  "文件类型": { en: "File Type", lv: 3 },
  "扩展名": { en: "Extension", lv: 3 },
  "加密": { en: "Encrypt", lv: 3 },
  "解密": { en: "Decrypt", lv: 3 },
  "指纹": { en: "Fingerprint", lv: 3 },
  "面部识别": { en: "Face Recognition", lv: 3 },
  "人脸识别": { en: "Face Recognition", lv: 3 },
  "解锁": { en: "Unlock", lv: 3 },
  "锁定": { en: "Lock", lv: 3 },
  "自动锁定": { en: "Auto-Lock", lv: 3 },
  "安全锁": { en: "Security Lock", lv: 3 },
  "密码强度": { en: "Password Strength", lv: 3 },
  "弱密码": { en: "Weak Password", lv: 3 },
  "强密码": { en: "Strong Password", lv: 3 },
  "双重验证": { en: "Two-Factor Auth", lv: 3 },
  "两步验证": { en: "Two-Step Verification", lv: 3 },
  "身份验证": { en: "Identity Verification", lv: 3 },
  "人脸认证": { en: "Face Verification", lv: 3 },
  "银行卡认证": { en: "Bank Card Verification", lv: 3 },
  "身份证": { en: "ID Card", lv: 3 },
  "证件照": { en: "ID Photo", lv: 3 },
  "违法和不良信息": { en: "Illegal Content", lv: 3 },
  "未成年人保护": { en: "Minor Protection", lv: 3 },
  "报告": { en: "Report", lv: 3 },
  "统计": { en: "Statistics", lv: 3 },
  "报表": { en: "Report", lv: 3 },
  "分析": { en: "Analysis", lv: 3 },
  "数据概览": { en: "Overview", lv: 3 },
  "趋势": { en: "Trend", lv: 3 },
  "图表": { en: "Chart", lv: 3 },
  "导出报告": { en: "Export Report", lv: 3 },
  "汇总": { en: "Summary", lv: 3 },
  "平均值": { en: "Average", lv: 3 },
  "百分比": { en: "Percentage", lv: 3 },
  "区间": { en: "Range", lv: 3 },
  "阈值": { en: "Threshold", lv: 3 },
  "实时": { en: "Real-Time", lv: 3 },
  "历史数据": { en: "Historical Data", lv: 3 },
  "数据源": { en: "Data Source", lv: 3 },
  "字段": { en: "Field", lv: 3 },
  "参数": { en: "Parameter", lv: 3 },
  "配置": { en: "Configuration", lv: 3 },
  "默认值": { en: "Default Value", lv: 3 },
  "自定义": { en: "Customize", lv: 3 },
  "个性化": { en: "Personalized", lv: 3 },
  "偏好": { en: "Preference", lv: 3 },
  "收藏夹管理": { en: "Manage Favorites", lv: 3 },
  "批量删除": { en: "Batch Delete", lv: 3 },
  "批量下载": { en: "Batch Download", lv: 3 },
  "批量上传": { en: "Batch Upload", lv: 3 },
  "批量编辑": { en: "Batch Edit", lv: 3 },
  "进度": { en: "Progress", lv: 3 },
  "进度条": { en: "Progress Bar", lv: 3 },
  "剩余时间": { en: "Time Remaining", lv: 3 },
  "已用时间": { en: "Elapsed Time", lv: 3 },
  "完成度": { en: "Completion", lv: 3 },
  "成功率": { en: "Success Rate", lv: 3 },
  "失败原因": { en: "Failure Reason", lv: 3 },
  "错误信息": { en: "Error Message", lv: 3 },
  "异常": { en: "Exception", lv: 3 },
  "警告": { en: "Warning", lv: 3 },
  "提示": { en: "Tip", lv: 3 },
  "确认删除": { en: "Confirm Delete", lv: 3 },
  "确认提交": { en: "Confirm Submit", lv: 3 },
  "不可撤销": { en: "Irreversible", lv: 3 },
  "谨慎操作": { en: "Proceed with Caution", lv: 3 },
  "授权": { en: "Authorize", lv: 3 },
  "已授权": { en: "Authorized", lv: 3 },
  "第三方": { en: "Third Party", lv: 3 },
  "关联账号": { en: "Linked Accounts", lv: 3 },
  "解绑账号": { en: "Unlink Account", lv: 3 },
  "数据迁移": { en: "Data Migration", lv: 3 },
  "数据清理": { en: "Data Cleanup", lv: 3 },
  "匿名化": { en: "Anonymization", lv: 3 },
  "脱敏": { en: "Masking", lv: 3 },
  "日志": { en: "Logs", lv: 3 },
  "操作日志": { en: "Audit Log", lv: 3 },
  "登录日志": { en: "Login Logs", lv: 3 },
  "查询": { en: "Query", lv: 3 },
  "检索": { en: "Retrieve", lv: 3 },
  "遍历": { en: "Traverse", lv: 3 },
  "映射": { en: "Mapping", lv: 3 },
  "解析": { en: "Parse", lv: 3 },
  "校验": { en: "Validate", lv: 3 },
  "格式": { en: "Format", lv: 3 },
  "编码": { en: "Encoding", lv: 3 },
  "解码": { en: "Decoding", lv: 3 },
  "压缩": { en: "Compress", lv: 3 },
  "解压": { en: "Decompress", lv: 3 },
  "转换": { en: "Convert", lv: 3 },
  "兼容": { en: "Compatible", lv: 3 },
  "版本兼容": { en: "Version Compatibility", lv: 3 },
  "升级": { en: "Upgrade", lv: 3 },
  "降级": { en: "Downgrade", lv: 3 },
  "回滚": { en: "Rollback", lv: 3 },
  "发布上线": { en: "Release", lv: 3 },
  "灰度发布": { en: "Canary Release", lv: 3 },
  "覆盖率": { en: "Coverage", lv: 3 },
  "命中率": { en: "Hit Rate", lv: 3 },
  "准确率": { en: "Accuracy", lv: 3 },
  "召回率": { en: "Recall Rate", lv: 3 },
  "性能": { en: "Performance", lv: 3 },
  "响应时间": { en: "Response Time", lv: 3 },
  "吞吐量": { en: "Throughput", lv: 3 },
  "并发": { en: "Concurrency", lv: 3 },
  "延迟": { en: "Latency", lv: 3 },
  "抖动": { en: "Jitter", lv: 3 },
  "稳定性": { en: "Stability", lv: 3 },
  "可靠性": { en: "Reliability", lv: 3 },
  "可用性": { en: "Availability", lv: 3 },
  "监控": { en: "Monitoring", lv: 3 },
  "告警": { en: "Alert", lv: 3 },
  "恢复机制": { en: "Recovery Mechanism", lv: 3 },
  "容错": { en: "Fault Tolerance", lv: 3 },
  "降级方案": { en: "Fallback Plan", lv: 3 },
  "应急预案": { en: "Contingency Plan", lv: 3 },
  "风险评估": { en: "Risk Assessment", lv: 3 },
  "合规": { en: "Compliance", lv: 3 },
  "审计": { en: "Audit", lv: 3 },
  "追溯": { en: "Traceability", lv: 3 },
  "备案": { en: "Filing", lv: 3 },
  "审批": { en: "Approval", lv: 3 },
  "待审批": { en: "Pending Approval", lv: 3 },
  "审批流": { en: "Approval Flow", lv: 3 },
  "抄送": { en: "CC", lv: 3 },
  "密送": { en: "BCC", lv: 3 },
  "收件人": { en: "Recipient", lv: 3 },
  "发件人": { en: "Sender", lv: 3 },
  "主题": { en: "Subject", lv: 3 },
  "附件": { en: "Attachment", lv: 3 },
  "正文": { en: "Body", lv: 3 },
  "草稿箱": { en: "Drafts", lv: 3 },
  "已发送": { en: "Sent", lv: 3 },
  "垃圾箱": { en: "Trash", lv: 3 },
  "回收站": { en: "Recycle Bin", lv: 3 },
  "日程": { en: "Schedule", lv: 3 },
  "提醒": { en: "Reminder", lv: 3 },
  "待办": { en: "To-Do", lv: 3 },
  "会议": { en: "Meeting", lv: 3 },
  "参会人": { en: "Attendee", lv: 3 },
  "主持人": { en: "Host", lv: 3 },
  "共享屏幕": { en: "Share Screen", lv: 3 },
  "录制": { en: "Record", lv: 3 },
  "字幕": { en: "Subtitles", lv: 3 },
  "静音": { en: "Mute", lv: 3 },
  "解除静音": { en: "Unmute", lv: 3 },
  "扬声器": { en: "Speaker", lv: 3 },
  "耳机": { en: "Headphones", lv: 3 },
  "在线状态": { en: "Online Status", lv: 3 },
  "离线": { en: "Offline", lv: 3 },
  "忙碌": { en: "Busy", lv: 3 },
  "离开": { en: "Away", lv: 3 },
  "请勿打扰": { en: "Do Not Disturb", lv: 3 },
  "状态更新": { en: "Status Update", lv: 3 },
  "个性签名": { en: "Bio", lv: 3 },
  "资料完整度": { en: "Profile Completeness", lv: 3 },
  "实名信息": { en: "Verified Info", lv: 3 },
  "证件信息": { en: "ID Information", lv: 3 },
  "收货信息": { en: "Shipping Info", lv: 3 },
  "发票信息": { en: "Invoice Info", lv: 3 },
  "抬头": { en: "Title", lv: 3 },
  "税号": { en: "Tax ID", lv: 3 },
  "开户行": { en: "Bank", lv: 3 },
  "账号信息": { en: "Account Info", lv: 3 },
  "资料修改": { en: "Edit Info", lv: 3 },
  "信息变更": { en: "Info Change", lv: 3 },
  "注销申请": { en: "Deletion Request", lv: 3 },
  "注销须知": { en: "Deletion Notice", lv: 3 },
  "注销后不可恢复": { en: "Non-Recoverable", lv: 3 },
  "协议": { en: "Agreement", lv: 3 },
  "条款": { en: "Terms", lv: 3 },
  "声明": { en: "Statement", lv: 3 },
  "规则": { en: "Rules", lv: 3 },
  "规范": { en: "Guidelines", lv: 3 },
  "指引": { en: "Guidance", lv: 3 },
  "公告": { en: "Announcement", lv: 3 },
  "通知中心": { en: "Notification Center", lv: 3 },
  "站务": { en: "Site Affairs", lv: 3 },
  "社区公约": { en: "Community Guidelines", lv: 3 },
  "内容规范": { en: "Content Standards", lv: 3 },
  "版权": { en: "Copyright", lv: 3 },
  "侵权": { en: "Infringement", lv: 3 },
  "投诉举报": { en: "Report Abuse", lv: 3 },
  "信息保护": { en: "Data Protection", lv: 3 },
  "数据安全": { en: "Data Security", lv: 3 },
  "网络安全": { en: "Cybersecurity", lv: 3 },
  "钓鱼网站": { en: "Phishing Site", lv: 3 },
  "诈骗": { en: "Fraud", lv: 3 },
  "风险提示": { en: "Risk Warning", lv: 3 },
  "安全提醒": { en: "Security Alert", lv: 3 },
  "账户保护": { en: "Account Protection", lv: 3 },
  "登录保护": { en: "Login Protection", lv: 3 },
  "支付保护": { en: "Payment Protection", lv: 3 },
  "保险": { en: "Insurance", lv: 3 },
  "理赔": { en: "Claim", lv: 3 },
  "赔付": { en: "Compensation", lv: 3 },
  "保障": { en: "Guarantee", lv: 3 },
  "保证金": { en: "Deposit", lv: 3 },
  "违约金": { en: "Penalty", lv: 3 },
  "押金": { en: "Deposit", lv: 3 },
  "租金": { en: "Rent", lv: 3 },
  "月租": { en: "Monthly Fee", lv: 3 },
  "年费": { en: "Annual Fee", lv: 3 },
  "手续费": { en: "Fee", lv: 3 },
  "服务费": { en: "Service Fee", lv: 3 },
  "管理费": { en: "Management Fee", lv: 3 },
  "税费": { en: "Tax", lv: 3 },
  "关税": { en: "Customs Duty", lv: 3 },
  "汇率": { en: "Exchange Rate", lv: 3 },
  "汇率换算": { en: "Currency Conversion", lv: 3 },
  "境外": { en: "Overseas", lv: 3 },
  "跨境": { en: "Cross-Border", lv: 3 },
  "海外购": { en: "Overseas Purchase", lv: 3 },
  "保税仓": { en: "Bonded Warehouse", lv: 3 },
  "清关": { en: "Customs Clearance", lv: 3 },
  "国际物流": { en: "International Shipping", lv: 3 },
  "转运": { en: "Transshipment", lv: 3 },
  "直邮": { en: "Direct Mail", lv: 3 },
  "包税": { en: "Tax Included", lv: 3 },
  "预购": { en: "Pre-Order", lv: 3 },
  "预售": { en: "Pre-Sale", lv: 3 },
  "尾款": { en: "Balance Payment", lv: 3 },
  "定金": { en: "Deposit", lv: 3 },
  "补差价": { en: "Price Difference", lv: 3 },
  "保价": { en: "Price Protection", lv: 3 },
  "限购": { en: "Purchase Limit", lv: 3 },
  "每人限购": { en: "Limit Per Person", lv: 3 },
  "随机": { en: "Random", lv: 3 },
  "概率": { en: "Probability", lv: 3 },
  "中奖率": { en: "Win Rate", lv: 3 },
  "获得": { en: "Obtain", lv: 3 },
  "消耗": { en: "Consume", lv: 3 },
  "扣除": { en: "Deduct", lv: 3 },
  "返还": { en: "Return", lv: 3 },
  "累计": { en: "Cumulative", lv: 3 },
  "排行": { en: "Ranking", lv: 3 },
  "名次": { en: "Rank", lv: 3 },
  "段位": { en: "Tier", lv: 3 },
  "赛季": { en: "Season", lv: 3 },
  "对战": { en: "Battle", lv: 3 },
  "匹配": { en: "Match", lv: 3 },
  "排位": { en: "Ranked", lv: 3 },
  "晋级": { en: "Promotion", lv: 3 },
  "淘汰": { en: "Elimination", lv: 3 },
  "胜率": { en: "Win Rate", lv: 3 },
  "连胜": { en: "Win Streak", lv: 3 },
  "段位保护": { en: "Tier Protection", lv: 3 },
  "巅峰赛": { en: "Peak Match", lv: 3 },
  "锦标赛": { en: "Tournament", lv: 3 },
  "冠军": { en: "Champion", lv: 3 },
  "亚军": { en: "Runner-Up", lv: 3 },
  "季军": { en: "Third Place", lv: 3 },
  "总决赛": { en: "Finals", lv: 3 },
  "预选赛": { en: "Qualifier", lv: 3 },
  "小组赛": { en: "Group Stage", lv: 3 },
  "淘汰赛": { en: "Knockout", lv: 3 },
  "半决赛": { en: "Semifinal", lv: 3 },
  "决赛": { en: "Final", lv: 3 },
  "比分": { en: "Score", lv: 3 },
  "直播": { en: "Live", lv: 3 },
  "回放": { en: "Replay", lv: 3 },
  "集锦": { en: "Highlights", lv: 3 },
  "解说": { en: "Commentary", lv: 3 },
  "弹幕": { en: "Danmaku", lv: 3 },
  "投币": { en: "Coin", lv: 3 },
  "三连": { en: "Triple Combo", lv: 3 },
  "一键三连": { en: "Like + Coin + Share", lv: 3 },
  "充电": { en: "Charge", lv: 3 },
  "打赏": { en: "Tip", lv: 3 },
  "礼物": { en: "Gift", lv: 3 },
  "粉丝团": { en: "Fan Club", lv: 3 },
  "铁粉": { en: "Loyal Fan", lv: 3 },
  "主播": { en: "Streamer", lv: 3 },
  "直播间": { en: "Live Room", lv: 3 },
  "上麦": { en: "On Stage", lv: 3 },
  "下麦": { en: "Off Stage", lv: 3 },
  "连麦": { en: "Connect", lv: 3 },
  "关注主播": { en: "Follow Streamer", lv: 3 },
  "订阅提醒": { en: "Subscribe Alerts", lv: 3 },
  "开播提醒": { en: "Live Alert", lv: 3 },
  "节目单": { en: "Program List", lv: 3 },
  "片单": { en: "Playlist", lv: 3 },
  "选集": { en: "Episodes", lv: 3 },
  "剧集": { en: "Series", lv: 3 },
  "番剧": { en: "Anime", lv: 3 },
  "漫画": { en: "Manga", lv: 3 },
  "小说": { en: "Novel", lv: 3 },
  "章节": { en: "Chapter", lv: 3 },
  "目录": { en: "Contents", lv: 3 },
  "书签": { en: "Bookmark", lv: 3 },
  "阅读进度": { en: "Reading Progress", lv: 3 },
  "连载": { en: "Serial", lv: 3 },
  "完结": { en: "Completed", lv: 3 },
  "更新中": { en: "Updating", lv: 3 },
  "番外": { en: "Extra", lv: 3 },
  "特典": { en: "Special", lv: 3 },
  "周边": { en: "Merchandise", lv: 3 },
  "手办": { en: "Figure", lv: 3 },
  "徽章": { en: "Badge", lv: 3 },
  "称号": { en: "Title", lv: 3 },
  "头衔": { en: "Title", lv: 3 },
  "称号系统": { en: "Title System", lv: 3 },
  "装扮": { en: "Decoration", lv: 3 },
  "皮肤": { en: "Skin", lv: 3 },
  "特效": { en: "Effect", lv: 3 },
  "道具": { en: "Item", lv: 3 },
  "装备": { en: "Equipment", lv: 3 },
  "强化": { en: "Enhance", lv: 3 },
  "升级材料": { en: "Upgrade Materials", lv: 3 },
  "碎片": { en: "Shards", lv: 3 },
  "合成": { en: "Craft", lv: 3 },
  "分解": { en: "Dismantle", lv: 3 },
  "出售": { en: "Sell", lv: 3 },
  "回购": { en: "Buy Back", lv: 3 },
  "交易行": { en: "Trade House", lv: 3 },
  "拍卖": { en: "Auction", lv: 3 },
  "一口价": { en: "Buyout", lv: 3 },
  "竞拍": { en: "Bid", lv: 3 },
  "出价": { en: "Offer", lv: 3 },
  "流拍": { en: "Failed Auction", lv: 3 },
  "成交": { en: "Deal", lv: 3 },
  "成交价": { en: "Deal Price", lv: 3 },
  "手续费比例": { en: "Fee Rate", lv: 3 },
  "结算周期": { en: "Settlement Cycle", lv: 3 },
  "提现到账": { en: "Withdrawal Arrival", lv: 3 },
  "提现失败": { en: "Withdrawal Failed", lv: 3 },
  "充值失败": { en: "Top-Up Failed", lv: 3 },
  "充值记录": { en: "Top-Up History", lv: 3 },
  "消费记录": { en: "Spending History", lv: 3 },
  "退款进度": { en: "Refund Progress", lv: 3 },
  "退款原因": { en: "Refund Reason", lv: 3 },
  "退款金额": { en: "Refund Amount", lv: 3 },
  "到账时间": { en: "Arrival Time", lv: 3 },
  "处理中": { en: "Processing", lv: 3 },
  "已完成退款": { en: "Refunded", lv: 3 },
  "退款失败": { en: "Refund Failed", lv: 3 },
  "订单状态": { en: "Order Status", lv: 3 },
  "订单编号": { en: "Order Number", lv: 3 },
  "订单备注": { en: "Order Note", lv: 3 },
  "下单时间": { en: "Order Time", lv: 3 },
  "付款时间": { en: "Payment Time", lv: 3 },
  "发货时间": { en: "Ship Time", lv: 3 },
  "收货时间": { en: "Delivery Time", lv: 3 },
  "完成时间": { en: "Completed Time", lv: 3 },
  "自动确认收货": { en: "Auto-Confirm", lv: 3 },
  "延长收货": { en: "Extend Receipt", lv: 3 },
  "申请售后": { en: "Request Service", lv: 3 },
  "售后服务": { en: "After-Sales Service", lv: 3 },
  "售后服务单": { en: "Service Order", lv: 3 },
  "维修单": { en: "Repair Order", lv: 3 },
  "故障描述": { en: "Issue Description", lv: 3 },
  "检测报告": { en: "Test Report", lv: 3 },
  "质检": { en: "Quality Check", lv: 3 },
  "验收": { en: "Acceptance", lv: 3 },
  "拒收": { en: "Reject", lv: 3 },
  "退回": { en: "Return", lv: 3 },
  "已退回": { en: "Returned", lv: 3 },
  "拦截": { en: "Intercept", lv: 3 },
  "改址": { en: "Change Address", lv: 3 },
  "改期": { en: "Reschedule", lv: 3 },
  "催单": { en: "Urge", lv: 3 },
  "客服介入": { en: "Support Escalation", lv: 3 },
  "纠纷": { en: "Dispute", lv: 3 },
  "仲裁": { en: "Arbitration", lv: 3 },
  "判决": { en: "Judgment", lv: 3 },
  "结案": { en: "Case Closed", lv: 3 },
  "调解": { en: "Mediation", lv: 3 },
  "协商": { en: "Negotiation", lv: 3 },
  "沟通": { en: "Communication", lv: 3 },
  "响应": { en: "Response", lv: 3 },
  "满意度": { en: "Satisfaction", lv: 3 },
  "评分": { en: "Rating", lv: 3 },
  "星级": { en: "Stars", lv: 3 },
  "五星好评": { en: "5-Star Review", lv: 3 },
  "匿名": { en: "Anonymous", lv: 3 },
  "公开评价": { en: "Public Review", lv: 3 },
  "隐私保护": { en: "Privacy Protection", lv: 3 },
  "个人信息": { en: "Personal Info", lv: 3 },
  "个人隐私": { en: "Personal Privacy", lv: 3 },
  "授权管理": { en: "Authorization Management", lv: 3 },
  "授权记录": { en: "Authorization Records", lv: 3 },
  "取消授权": { en: "Revoke", lv: 3 },
  "授权期限": { en: "Authorization Period", lv: 3 },
  "权限范围": { en: "Permission Scope", lv: 3 },
  "数据用途": { en: "Data Usage", lv: 3 },
  "数据共享": { en: "Data Sharing", lv: 3 },
  "数据删除": { en: "Data Deletion", lv: 3 },
  "删除账号": { en: "Delete Account", lv: 3 },
  "账号申诉": { en: "Account Appeal", lv: 3 },
  "封禁": { en: "Ban", lv: 3 },
  "解封": { en: "Unban", lv: 3 },
  "违规": { en: "Violation", lv: 3 },
  "违规记录": { en: "Violation History", lv: 3 },
  "处罚": { en: "Penalty", lv: 3 },
  "警告记录": { en: "Warning History", lv: 3 },
  "禁言": { en: "Mute", lv: 3 },
  "限制登录": { en: "Login Restricted", lv: 3 },
  "限制交易": { en: "Trading Restricted", lv: 3 },
  "信用分": { en: "Credit Score", lv: 3 },
  "信用记录": { en: "Credit History", lv: 3 },
  "失信": { en: "Default", lv: 3 },
  "恢复信用": { en: "Credit Recovery", lv: 3 }
};
